## config for CLIP snakemake pipeline #
 
## credit: Neel Mukherjee

FA:
  "GRCh37.p13.genome.fa"
THREE_PRIME_ADAPTER_SEQUENCE:
  "TGGAATTCTCGGGTGCCAAGG"
FIVE_PRIME_ADAPTER_SEQUENCE:
  "AATGATACGGCGACCACCGACAGGTTCAGAGTTCTACAGTCCGACGATC"
NINETEEN_NUCLEOTIDE_MARKER_SEQUENCE:
  "CGTACGCGGGTTTAAACGA"
TWENTY_FOUR_NUCLEOTIDE_MARKER_SEQUENCE:
  "CGTACGCGGAATAGTTTAAACTGT"
ICLIP_ADAPTER:
  "AGATCGGAAGAGCGGTTCAG"
HITSCLIP_3ADAPTER:
  "TCGTATGCCGTCTTCTGCTTG"
HITSCLIP_5ADAPTER:
  "AATGATACGGCGACCACCGA"
KIT_5ADAPTER:
  "GTTCAGAGTTCTACAGTCCGACGATC"
SPECIAL_AD_1:
  "AGATCGGAAGAGCACACGTCTG"
SPECIAL_AD_2:
  "CTCGTATGCCGTCTTCTGCTTG"
SPECIAL_AD_3:
  "TGAGATCGGAAGAGCGGTTCAG"
THR:
  "4"
GTF:
  "gencode.v19.annotation.gtf"
SEGE_IDX:
  "hg19.segemehl.idx"
